# Generated by Django 3.2.6 on 2022-03-26 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=50)),
                ('clg_yr', models.CharField(choices=[('First Year', 'Firstyear'), ('second Year', 'Secondyear'), ('third Year', 'Thirdyear'), ('fourth Year', 'Fouryear')], default='First Year', max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clg_dataapi.branch')),
            ],
        ),
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('SId', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=50)),
                ('clg_yr', models.CharField(choices=[('First Year', 'Firstyear'), ('second Year', 'Secondyear'), ('third Year', 'Thirdyear'), ('fourth Year', 'Fouryear')], default='First Year', max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clg_dataapi.branch')),
                ('teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clg_dataapi.teacherdata')),
            ],
        ),
    ]
