# Generated by Django 3.2.6 on 2022-03-26 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clg_dataapi', '0002_alter_studentdata_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='clg_dataapi.branch'),
        ),
    ]
